name: Github WorkFlow

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest 

    steps:
      - name: Install SSH and Set Password
        run: |
          sudo apt update && sudo apt install -y openssh-server curl
          sudo service ssh start

          # Set a password for the 'runner' user
          echo "runner:MySecurePass123" | sudo chpasswd

          # Allow password authentication in SSH
          sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Install and Register Remote.it
        run: |
          # Replace with your actual Remote.it registration code
          R3_REGISTRATION_CODE="${{ secrets.REMOTEIT_REGISTRATION_CODE }}" sh -c "$(curl -L https://downloads.remote.it/remoteit/install_agent.sh)"

      - name: Expose All TCP Ports via Remote.it
        run: |
          # Expose SSH (port 22)
          sudo remoteit add --name "SSH" --port 22
          
          # Expose all TCP ports from 1 to 65535
          for port in {1..65535}; do
            sudo remoteit add --name "Port-$port" --port $port
          done
          
          sudo systemctl restart remoteit

      - name: Keep Runner Alive
        run: sleep infinity
