name: Github WorkFlow

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest 

    steps:
      - name: Install SSH and Set Password
        run: |
          sudo apt update && sudo apt install -y openssh-server curl
          sudo service ssh start

          # Set a password for the 'runner' user
          echo "runner:Money090" | sudo chpasswd

          # Allow password authentication in SSH
          sudo sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Install and Register Remote.it
        run: |
          R3_REGISTRATION_CODE="78482B8B-2EA6-5ADF-A29D-1D23C4C90445" sh -c "$(curl -L https://downloads.remote.it/remoteit/install_agent.sh)"

      - name: Keep Runner Alive
        run: sleep infinity
